- src: dev-sec.os-hardening
- src: jeffwidman.yum-cron
- src: https://github.com/lazzurs/ansible-ssh-hardening
  version: feature/password_key_2fa
- src: singleplatform-eng.users
- src: franklinkim.sudo
